version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: marshmallow
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: prompt-toolkit
    versions:
    - 3.0.14
    - 3.0.15
    - 3.0.16
    - 3.0.17
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: environs
    versions:
    - 9.3.0
    - 9.3.1
  - dependency-name: motor
    versions:
    - 2.3.0
    - 2.3.1
